name: CI

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/CI.yml
      - src/**
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/CI.yml
      - src/**

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
    steps:
    - uses: actions/checkout@v2
    - name: Generate VS solution
      working-directory: src
      run: |
        reg add "HKLM\SOFTWARE\WOW6432Node\Microsoft\VisualStudio\10.0\Projects\{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}" /v DefaultProjectExtension /t REG_SZ /d vcproj /f
        .\devtools\bin\vpc.exe /csso +everything /mksln csso.sln /f
        gc .\sln_fix.txt | ac .\csso.sln
    - uses: microsoft/setup-msbuild@v1
    - name: Build
      run: msbuild src\csso.sln /m /p:Configuration=Release /t:"Clean;Build
        
    - name: Prepare artifacts
      id: prepare_artifacts
      run: |
        robocopy mp\game\bin          artifacts\bin\bin          /xf *.pdb /r:0 /w:0
        robocopy mp\game\csso\bin artifacts\bin\csso\bin /xf *.pdb /r:0 /w:0
        robocopy mp\game\bin          artifacts\pdb\bin              *.pdb /r:0 /w:0
        robocopy mp\game\csso\bin artifacts\pdb\csso\bin     *.pdb /r:0 /w:0
        If ($LastExitCode -le 7) { echo "LastExitCode = $LastExitCode";$LastExitCode = 0 }
        echo "::set-output name=short_commit_sha::$(git rev-parse --short HEAD)"
    - name: Upload bin artifacts
      uses: actions/upload-artifact@v2
      with:
        name: bin_${{ runner.os }}-${{ steps.prepare_artifacts.outputs.short_commit_sha }}
        path: artifacts\bin
        if-no-files-found: error
    - name: Upload pdb artifacts
      uses: actions/upload-artifact@v2
      with:
        name: pdb_${{ runner.os }}-${{ steps.prepare_artifacts.outputs.short_commit_sha }}
        path: artifacts\pdb
        if-no-files-found: error
